name: Quality checks

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/*.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint-command:
          - npm run lint:md
          - npm run lint:relative-urls
          - npm run lint:consistency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Ensure consistency
        run: npm run lint
